steps:

  # Build the Docker image
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'docker-build-status'
    args:
    - --destination=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/foo/${_ENVIRONMENT}:$COMMIT_SHA
    - --destination=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/foo/${_ENVIRONMENT}:latest
    - --cache=true
    - --cache-ttl=24h
    - --build-arg=MY_SECRET
    secretEnv: ["MY_SECRET"]

  # Deploy `foo` to container running on cloudrun
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-app-to-cloud-run'
    waitFor: ['docker-build-status']
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      if gcloud run deploy foo-${_ENVIRONMENT} \
        --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/foo/${_ENVIRONMENT}:$COMMIT_SHA \
        --region=${_REGION} \
        --service-account=${_SERVICE_ACCOUNT} \
        --execution-environment=gen2 \
        --min-instances=1 \
        --max-instances=3 \
        --cpu=2 \
        --memory=1Gi \
        --timeout=600 \
        --concurrency=400 \
        --platform managed \
        --cpu-boost \
        --session-affinity \
        --allow-unauthenticated

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

substitutions:
  _ENVIRONMENT: "dev"
  _PROJECT_NUMBER: "YOUR_PROJECT_NUMBER"
  _PROJECT_ID: "YOUR_PROJECT_ID"
  _SERVICE_ACCOUNT: "cloudrun-svc-acc"
  _REGION: "us-central1"

availableSecrets:
  secretManager:
    - versionName: >-
        projects/${_PROJECT_NUMBER}/secrets/my-secret-${_ENVIRONMENT}/versions/latest
      env: "MY_SECRET"

 
